services:
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001" # Консоль управления
    environment:
      MINIO_ROOT_USER: qwerdsaf
      MINIO_ROOT_PASSWORD: 88888888556556556
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network
    restart: always

  # Worker сервисы
  worker1:
    build:
      context: ./oc-agent-javac
    image: compiler-worker:latest
    container_name: worker1
    ports:
      - "5001:5000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
    depends_on:
      - minio
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker2:
    build:
      context: ./oc-agent-javac
    image: compiler-worker:latest
    container_name: worker2
    ports:
      - "5002:5000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
    depends_on:
      - minio
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker3:
    build:
      context: ./oc-agent-javac
    image: compiler-worker:latest
    container_name: worker3
    ports:
      - "5003:5000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
    depends_on:
      - minio
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  worker4:
    build:
      context: ./oc-agent-javac
    image: compiler-worker:latest
    container_name: worker4
    ports:
      - "5004:5000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
    depends_on:
      - minio
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  worker5:
    build:
      context: ./oc-agent-javac
    image: compiler-worker:latest
    container_name: worker5
    ports:
      - "5005:5000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
    depends_on:
      - minio
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  worker6:
    build:
      context: ./oc-agent-javac
    image: compiler-worker:latest
    container_name: worker6
    ports:
      - "5006:5000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
    depends_on:
      - minio
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  worker7:
    build:
      context: ./oc-agent-javac
    image: compiler-worker:latest
    container_name: worker7
    ports:
      - "5007:5000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
    depends_on:
      - minio
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  worker8:
    build:
      context: ./oc-agent-javac
    image: compiler-worker:latest
    container_name: worker8
    ports:
      - "5008:5000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
    depends_on:
      - minio
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  worker9:
    build:
      context: ./oc-agent-javac
    image: compiler-worker:latest
    container_name: worker9
    ports:
      - "5009:5000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
    depends_on:
      - minio
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  worker10:
    build:
      context: ./oc-agent-javac
    image: compiler-worker:latest
    container_name: worker10
    ports:
      - "5010:5000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
    depends_on:
      - minio
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3


  dispatcher:
    build:
      context: ./dispatcher
    image: dispatcher:latest
    container_name: dispatcher
    ports:
      - "8081:8081"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
      - WORKER_URLS=http://worker1:5000,http://worker2:5000,http://worker3:5000,http://worker4:5000,http://worker5:5000,http://worker6:5000,http://worker7:5000,http://worker8:5000,http://worker9:5000,http://worker10:5000
    depends_on:
      - minio
      - worker1
      - worker2
      - worker3
      - worker4
      - worker5
      - worker6
      - worker7
      - worker8
      - worker9
      - worker10
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  minio-data:
