services:
  redis:
    image: "redis:6.2"
    container_name: redis
    ports:
      - "6379:6379"  # Порт для Redis
    networks:
      - app-network
    restart: always

  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001" # Консоль управления
    environment:
      MINIO_ROOT_USER: qwerdsaf
      MINIO_ROOT_PASSWORD: 88888888556556556
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network
    restart: always

  # Worker сервисы
  worker1:
    build:
      context: ../oc-agent-javac
    image: compiler-worker:latest
    container_name: worker1
    ports:
      - "5001:5000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
    depends_on:
      - minio
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  python-worker1:
    build:
      context: ./oc-agent-python-java
    image: python-java-worker:latest
    container_name: python-worker1
    ports:
      - "6001:6000" # Внутренний порт 6000, внешний 6001
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
    depends_on:
      - minio
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  dispatcher:
    build:
      context: ./dispatcher
    image: dispatcher:latest
    container_name: dispatcher
    ports:
      - "8081:8081"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=qwerdsaf
      - MINIO_SECRET_KEY=88888888556556556
      - MINIO_BUCKET_NAME=my-bucket
      - WORKER_URLS=http://worker1:5000
      - PYTHON_WORKER_URLS=http://python-worker1:6000
    depends_on:
      - minio
      - worker1
      - python-worker1
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  minio-data:
