global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8082' ]
